"""add graph nodes and edges

Revision ID: 2aac0fa0f3fb
Revises: 8b039903f255
Create Date: 2026-07-09 23:55:10.131725
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2aac0fa0f3fb"
down_revision: str | None = "8b039903f255"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=1024), nullable=False),
        sa.Column("target_key", sa.String(length=1024), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_graph_edges_repo_source", "graph_edges", ["repository_id", "source_key"], unique=False
    )
    op.create_index(
        op.f("ix_graph_edges_repository_id"), "graph_edges", ["repository_id"], unique=False
    )
    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=1024), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("path", sa.String(length=2048), nullable=True),
        sa.Column("parent_key", sa.String(length=1024), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "key", name="uq_graph_node_repo_key"),
    )
    op.create_index(
        "ix_graph_nodes_repo_level", "graph_nodes", ["repository_id", "level"], unique=False
    )
    op.create_index(
        op.f("ix_graph_nodes_repository_id"), "graph_nodes", ["repository_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_graph_nodes_repository_id"), table_name="graph_nodes")
    op.drop_index("ix_graph_nodes_repo_level", table_name="graph_nodes")
    op.drop_table("graph_nodes")
    op.drop_index(op.f("ix_graph_edges_repository_id"), table_name="graph_edges")
    op.drop_index("ix_graph_edges_repo_source", table_name="graph_edges")
    op.drop_table("graph_edges")
    # ### end Alembic commands ###
