"""add decisions table

Revision ID: e8e8999e405e
Revises: ed7d8cd70a0a
Create Date: 2026-07-09 22:33:47.266688
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e8e8999e405e"
down_revision: str | None = "ed7d8cd70a0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=512), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("tradeoffs", sa.Text(), nullable=False),
        sa.Column("alternatives", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decisions_repository_id"), "decisions", ["repository_id"], unique=False
    )
    op.create_index(
        "ix_decisions_repository_order", "decisions", ["repository_id", "order_index"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_decisions_repository_order", table_name="decisions")
    op.drop_index(op.f("ix_decisions_repository_id"), table_name="decisions")
    op.drop_table("decisions")
    # ### end Alembic commands ###
